runtime: python39
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT
vpc_access_connector:
  name: projects/vocal-ceiling-278518/locations/us-central1/connectors/vpc-db1
handlers:
- url: /post_message
  script: auto
  login: admin